"""add population column

Revision ID: 092842e0244c
Revises: 24ffa861f7cd
Create Date: 2024-08-09 11:49:32.035461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092842e0244c'
down_revision = '24ffa861f7cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_column('population')

    # ### end Alembic commands ###
