"""country table

Revision ID: 24ffa861f7cd
Revises: 
Create Date: 2024-02-24 22:27:56.462450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ffa861f7cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('capital', sa.String(length=120), nullable=False),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_country_capital'), ['capital'], unique=True)
        batch_op.create_index(batch_op.f('ix_country_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('country', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_country_name'))
        batch_op.drop_index(batch_op.f('ix_country_capital'))

    op.drop_table('country')
    # ### end Alembic commands ###
